# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 378c2a3ad64d6b599cdd04c09a4093d7e875a1ccadc27becafc29b76dd99a7536934480b2dc586aabcd6dfb5c53d1932fda6532c6e7903233b64456f8ff66e65

test:
  secret_key_base: 19e08aa78c30f97cf6e356fa7b529eaa1a3e44f06aecab3ffac85e305c3368ccdaf95f40ff021d81f0d345514ab4bedd569174570a8ac368137a6321a33cc288

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
